services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - .env

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    env_file:
      - .env

  mongodb:
    image: mongo:7
    container_name: mongodb
    ports:
      - "27017:27017"
    env_file:
      - .env

  gateway-service:
    build:
      context: ./apps/gateway-service
    container_name: gateway-service
    ports:
      - "3000:3000"
    env_file:
      - .env

  auth-service:
    build:
      context: ./apps/auth-service
    container_name: auth-service
    ports:
      - "3001:3001"
    env_file:
      - .env

  path-service:
    build:
      context: ./apps/path-service
    container_name: path-service
    ports:
      - "3002:3002"
    env_file:
      - .env

  follow-request-service:
    build:
      context: ./apps/follow-request-service
    container_name: follow-request-service
    ports:
      - "3003:3003"
    depends_on:
      - rabbitmq
    env_file:
      - .env

  tracking-service:
    build:
      context: ./apps/tracking-service
    container_name: tracking-service
    depends_on:
      - rabbitmq    
    env_file:
      - .env  
