apiVersion: apps/v1
kind: Deployment

metadata:
  name: tracking-service
  namespace: fmp

spec:
  replicas: 1

  strategy:
    type: RollingUpdate

    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

  selector:
    matchLabels:
      app: tracking-service

  template:
    metadata:
      labels:
        app: tracking-service

    spec:
      containers:
        - name: tracking-service
          image: venerableharsha/tracking-service:latest
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: secret          
          ports:
            - name: http
              containerPort: 3004

          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"

            limits:
              cpu: "100m"
              memory: "128Mi"

          env:
            - name: RABBITMQ_URL
              value: "amqp://rabbitmq:5672"

            - name: DATABASE_URL
              value: "mongodb://admin:password@mongodb:27017/fmp?authSource=admin"

            - name: REDIS_URL
              value: "redis://redis:6379"
