apiVersion: apps/v1
kind: Deployment

metadata:
  name: follow-request-service
  namespace: fmp

spec:
  replicas: 1
  strategy:
    type: RollingUpdate

    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: follow-request-service

  template:
    metadata:
      labels:
        app: follow-request-service

    spec:
      containers:
        - name: follow-request-service
          image: venerableharsha/follow-request-service:latest
          imagePullPolicy: Always          
          envFrom:
          - secretRef:
              name: follow-request-secret

          - configMapRef:
              name: follow-request-config
          ports:
            - containerPort: 3003

          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"

            limits:
              cpu: "100m"
              memory: "128Mi"
          
          env:
            - name: RABBITMQ_URL
              value: amqp://rabbitmq:5672
            - name: DATABASE_URL
              value: "mongodb://admin:password@mongodb:27017/fmp?authSource=admin"