apiVersion: v1
kind: Secret

metadata:
  name: follow-request-secret
  namespace: fmp

type: Opaque

stringData:
  DATABASE_URL : "mongodb://admin:password@localhost:27017/fmp?authSource=admin"
GOOGLE_CLIENT_ID: "REPLACE_ME"
GOOGLE_CLIENT_SECRET: "REPLACE_ME"
GOOGLE_CALLBACK_URL : "REPLACE_ME"